# Generated by Django 5.2 on 2025-04-11 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aniversariante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('data', models.DateField()),
                ('idade', models.PositiveIntegerField()),
                ('CPF', models.CharField(max_length=14, unique=True)),
                ('boloPreferido', models.CharField(max_length=20)),
                ('sexo', models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino'), ('O', 'Outros')])),
            ],
        ),
    ]
